feat: added optional description to Icon Items
tmorin/plantuml-generator pull request #1
Opened 2022-07-22 17:04 UTC by chalmagr

After attempting to check how the elements were created in the libs repository found this way instead to update them all... however, I am not able to run the scripts as there is some error during the build

```log
 => [builder 6/6] RUN cargo build --release --features vendored-openssl
 => => # error: could not compile `cc`
 => => # Caused by:
 => => #   process didn't exit successfully: `rustc --crate-name cc --edition=2018 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.69/src/lib.rs --error-format=json --json=diagnostic-rendered-an
 => => # si,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=4210e52f53f6b87b -C extra-filename=-4210e52f53f6b87b --out-dir /usr/sr
 => => # c/plantuml-generator/target/release/deps -L dependency=/usr/src/plantuml-generator/target/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
 => => # warning: build failed, waiting for other jobs to finish...
```

2022-07-26 15:19 UTC, chalmagr commented
@tmorin not sure if you got this PR request in your radar. I think having the ability to display a description is very important to make a diagram readable without relying on the icons / titles only - there is more to the story behind that

2022-07-26 20:07 UTC, tmorin commented
Hi @chalmagr

Thank you for the PR.

Let's see how CI will manage it ;)

Best regards

2022-07-27 18:10 UTC, tmorin requested changes

2022-07-27 18:10 UTC, tmorin commented on src/cmd/library/generate/templates/item_snippet.rs
> +{{ data.procedure_name }}('{{ data.variable_name }}', '{{ data.primary_label }}', '{{ data.technical_label | default(value="an optional tech label"), '{{ data.description_label | default(value="an op
hi @chalmagr ,

I think there is a missing `}}'` between `"an optional tech label")` and `, '{{ data.description_label`.

If you cannot run test locally, you could maybe try to do it with the GitHub action.

Best regards

2022-07-28 02:23 UTC, chalmagr commented on src/cmd/library/generate/templates/item_snippet.rs
> +{{ data.procedure_name }}('{{ data.variable_name }}', '{{ data.primary_label }}', '{{ data.technical_label | default(value="an optional tech label"), '{{ data.description_label | default(value="an op
Fixed this issue, but the workflow seems to be failing due to some png files not found… not fully sure what is happening there as I am not familiar with the tests or Rust. 
if you can see the actions in my project maybe that can help? Will see if I can run locally…

2022-07-28 04:32 UTC, chalmagr commented on src/cmd/library/generate/templates/item_snippet.rs
> +{{ data.procedure_name }}('{{ data.variable_name }}', '{{ data.primary_label }}', '{{ data.technical_label | default(value="an optional tech label"), '{{ data.description_label | default(value="an op
Still having the issue there but not sure why... I was able to create the generator image locally and currently generating all the icons for gcp (pretty much same as what I had initially created using ```find ... -exec sed -i ...```

Hopefully this test is you can help with? it seems it's not generating the image for the svg, but this doesn't seem connected with this changes ... below are the failures I see in the github actions tab

```
failures:
    cmd::library::generate::generator::tests::test_full_generation
    cmd::library::generate::generator::tests::test_icon_reference
    cmd::library::generate::tasks::item::item_icon::test::test_create_resources_with_inkscape

test result: FAILED. 38 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 9.90s
```

2022-07-30 13:48 UTC, tmorin commented
Hi @chalmagr ,

I fixed the main branch. The Inkscape version was not the right one in CI.

You can rebase from the main branch.

Best regards

2022-08-01 00:28 UTC, chalmagr commented
After pulling in the changes all tests are good

2022-08-02 14:02 UTC, merged